app = "kcj-progress"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8000"
  SQLITE_DB_PATH = "/data/calories.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "15s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[mounts]]
  source = "calorie_data"
  destination = "/data"
